pull_request_rules:
  - name: Add Label approval + 1
    conditions:
      - "#approved-reviews-by=1"
      - base=master
      - label!=WIP
    actions:
      label:
        add: ["approval + 1"]

  - name: Add Label approval + 2
    conditions:
      - "#approved-reviews-by=2"
      - base=master
      - label!=WIP
    actions:
      label:
        add: ["approval + 2"]
        remove: ["approval + 1"]

  - name: Add Label needs reveiw
    conditions:
      - "#changes-requested-reviews-by=0"
      - base=master
      - label!=WIP
    actions:
      label:
        add: ["needs review"]